---
- name: Configure a login banner on Cisco IOS with text "First banner with Ansible."
  hosts: cisco
  gather_facts: false
  vars_files:
    - banner_vars.yml
  tasks:
    - name: Configure a login banner on Cisco IOS with text "First banner with Ansible."
      cisco.ios.ios_banner:
        banner: "{{ banner_type }}"
        text: "{{ network_banner }}"
        state: present
